### ISSUE TITLE
undefined reference to a symbol from shared library

### ISSUE THREAD

**Issue by marxin** [davidlattimore/wild#931]
I noticed the following library build fails since d392e9d87ffc74536b11133aed501f1a60268d3b:

```
$ git clone https://github.com/rhash/RHash.git
$ cd RHash
$ ./configure --enable-openssl
$ make -j8
$ cc calc_sums.o hash_print.o common_func.o hash_update.o file.o file_mask.o file_set.o find_file.o hash_check.o output.o parse_cmdline.o rhash_main.o win_utils.o librhash/librhash.so.1.4.6   -o rhash -Wl,--no-allow-shlib-undefined  -B ~/Programming/wild
WARNING: wild: --plugin /usr/lib64/gcc/x86_64-suse-linux/15/liblto_plugin.so is not yet supported
Error: Failed to activate librhash/librhash.so.1.4.6 (4352 (17/0))
  Caused by:
    undefined reference to `WHIRLPOOL_Init` from librhash/librhash.so.1.4.6 (4352 (17/0))

collect2: error: ld returned 255 exit status
```

**Comment by mati865** [comment]
Proably a duplicate of https://github.com/davidlattimore/wild/issues/897

**Comment by marxin** [comment]
Yeah, thanks, looks like a dup.

**Comment by marxin** [comment]
Fixed with #967.
